# Generated by Django 4.0.4 on 2022-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_box_id', models.CharField(max_length=32)),
                ('place_name', models.TextField(blank=True, max_length=16, null=True)),
                ('traffic', models.TextField(blank=True, max_length=64, null=True)),
                ('accomdation', models.TextField(blank=True, max_length=64, null=True)),
                ('food', models.TextField(blank=True, max_length=64, null=True)),
                ('activity', models.TextField(blank=True, max_length=64, null=True)),
                ('sightseeing', models.TextField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
