# Generated by Django 4.0.4 on 2022-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='image',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
    ]
