# Generated by Django 4.0.4 on 2022-05-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0003_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
