# Generated by Django 4.0.4 on 2022-05-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0005_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
