# Generated by Django 4.0.4 on 2022-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0006_delete_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel_box',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
    ]
