# Generated by Django 4.0.4 on 2022-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0007_rename_image_travel_box_image_1_travel_box_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_box_id', models.CharField(max_length=32)),
                ('user_image_1', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('user_image_2', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('user_image_3', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
            ],
        ),
    ]
