# Generated by Django 4.0.4 on 2022-05-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0008_getpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpic',
            name='box_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbox.travel_box'),
        ),
    ]
