# Generated by Django 4.0.4 on 2022-05-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0010_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_box',
            name='accomdation',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='activity',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='food',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='sightseeing',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='traffic',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
