# Generated by Django 4.0.4 on 2022-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0011_alter_travel_box_accomdation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='image_head',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='script',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='sub_title',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
