# Generated by Django 4.0.4 on 2022-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0012_travel_box_image_head_travel_box_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpic',
            name='check_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
