# Generated by Django 4.0.3 on 2022-05-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0013_getpic_check_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chulwon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_accomdation', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_food', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_activity', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_sightseeing', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
            ],
        ),
    ]
