# Generated by Django 4.0.3 on 2022-05-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0014_chulwon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_accomdation', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_food', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_activity', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('image_sightseeing', models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/')),
                ('local_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbox.travel_box')),
            ],
        ),
        migrations.DeleteModel(
            name='Chulwon',
        ),
    ]
