# Generated by Django 4.0.3 on 2022-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0015_local_delete_chulwon'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='image_accomdation',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_activity',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_food',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='travel_box',
            name='image_sightseeing',
            field=models.ImageField(blank=True, upload_to='landing/images/%Y/%m/%d/%H/'),
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
