# Generated by Django 4.0.3 on 2022-05-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0016_travel_box_image_accomdation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpic',
            name='check_num',
        ),
    ]
