# Generated by Django 4.0.4 on 2022-05-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0017_remove_getpic_check_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='addr_accomdation',
            field=models.TextField(blank=True, max_length=2024, null=True),
        ),
    ]
