# Generated by Django 4.0.4 on 2022-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0018_travel_box_addr_accomdation'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel_box',
            name='sightseeing_addr_link',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='travel_box',
            name='addr_accomdation',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
