# Generated by Django 4.0.4 on 2022-05-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0019_travel_box_sightseeing_addr_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel_box',
            name='sightseeing_addr_link',
        ),
    ]
