# Generated by Django 4.0.4 on 2022-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbox', '0020_remove_travel_box_sightseeing_addr_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpic',
            name='checked',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
